still cahnges to status and plan

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -69,17 +69,17 @@ jobs:
       - name: Terraform plan
         id: plan
         run: terraform plan -no-color -input=false -out=planfile 
-        continue-on-error: true 
+        #continue-on-error: true 
 
-      - name: Terraform plan status
-        id: plan_status
-        if: always()
-        run:  |
-          echo "Terraform plan outcome: ${{ steps.plan.outcome }}"
-          if [ "${{ steps.plan.outcome }}" != "success" ]; then
-            echo "Plan failed. Check logs in step: Terraform plan (id: plan)"
-            exit 1
-          fi
+      # - name: Terraform plan status
+      #   id: plan_status
+      #   if: always()
+      #   run:  |
+      #     echo "Terraform plan outcome: ${{ steps.plan.outcome }}"
+      #     if [ "${{ steps.plan.outcome }}" != "success" ]; then
+      #       echo "Plan failed. Check logs in step: Terraform plan (id: plan)"
+      #       exit 1
+      #     fi
 
       - name: Terraform Apply 
         id: apply
