kms changes

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -21,7 +21,7 @@ permissions:
 env:
   BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
   AWS_REGION: us-east-1
-  EKS_CLUSTER: vprofile-eks
+  EKS_CLUSTER: vprofile-eks-test
 
 jobs:
   terraform:
@@ -72,12 +72,12 @@ jobs:
         if: steps.plan.outcome != 'success'
         run: exit 1
 
-      # - name: Terraform plan status
-      #   id: plan_status
-      #   if: failure()
-      #   run: |
-      #     echo "Plan failed in step id=plan. Scroll up to see the exact Terraform error output."
-      #     exit 1
+      - name: Terraform plan status
+        id: plan_status
+        if: failure()
+        run: |
+          echo "Plan failed in step id=plan. Scroll up to see the exact Terraform error output."
+          exit 1
 
       - name: Terraform apply
         if: github.ref == 'refs/heads/main' && github.event_name == 'push'
