changes to plan and staus

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -68,23 +68,29 @@ jobs:
 
       - name: Terraform plan
         id: plan
-        run: terraform plan -no-color -input=false -out=planfile
-        continue-on-error: true
+        run: terraform plan -no-color -input=false -out=planfile 
+        continue-on-error: true 
 
       - name: Terraform plan status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1 
+        id: plan_status
+        if: always()
+        run:  |
+          echo "Terraform plan outcome: ${{ steps.plan.outcome }}"
+          if [ "${{ steps.plan.outcome }}" != "success" ]; then
+            echo "Plan failed. Check logs in step: Terraform plan (id: plan)"
+            exit 1
+          fi
 
       - name: Terraform Apply 
-        id: apple
+        id: apply
         if: github.ref == 'refs/heads/main' && github.event_name == 'push' 
         run: terraform apply -auto-approve -input=false -parallelism=1 planfile 
 
       - name: Get kube config file 
         id: getconfig 
-        if: steps.apple.outcome == 'success' 
+        if: steps.apply.outcome == 'success' 
         run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER }}
 
       - name: Install Ingress controller 
-        if: steps.apple.outcome == 'success' && steps.getconfig.outcome == 'success'
+        if: steps.apply.outcome == 'success' && steps.getconfig.outcome == 'success'
         run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.14.3/deploy/static/provider/aws/deploy.yaml
